stages:
  train:
    cmd: python src/train.py
    deps:
    - submission
    - label_book
    - src/train.py
    outs:
    - ckpts/best_model.data-00000-of-00001
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - submission
    - label_book
    - src/evaluate.py
    - ckpts/best_model.data-00000-of-00001
    metrics:
    - scores.json:
        cache: false